language: node_js

node_js:
  - '8'
script: npm run build

deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master

env:
  global:
    - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/max/max.wtf.git
