language: node_js

node_js:
  - '8'
script: npm run build

deploy:
  on:
    branch: master
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true

env:
  global:
    - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/max/max.git
